# Generated by Django 5.2.7 on 2025-10-17 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], default='BREAKFAST', max_length=20)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('calories_current', models.IntegerField(default=0)),
                ('calories_goal', models.IntegerField(default=2000)),
                ('carbs_current', models.IntegerField(default=0)),
                ('carbs_goal', models.IntegerField(default=100)),
                ('protein_current', models.IntegerField(default=0)),
                ('protein_goal', models.IntegerField(default=130)),
                ('fiber_current', models.IntegerField(default=0)),
                ('fiber_goal', models.IntegerField(default=55)),
                ('fat_current', models.IntegerField(default=0)),
                ('fat_goal', models.IntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_user_date_nutrition_log')],
            },
        ),
    ]
