# Generated by Django 5.2.6 on 2025-11-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('instructions_md', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('REPS', 'Repetitions'), ('SECONDS', 'Seconds'), ('HOLD', 'Isometric Hold'), ('DISTANCE', 'Distance')], default='REPS', max_length=16)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps_or_seconds', models.PositiveIntegerField(default=10)),
                ('default_rest_sec', models.PositiveIntegerField(default=30)),
                ('equipment', models.CharField(blank=True, max_length=128)),
                ('camera_config_json', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=8)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('alt_text', models.CharField(blank=True, max_length=140)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='exerciseList.exercise')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('exercise', 'order')},
            },
        ),
    ]
