# Generated by Django 5.2.6 on 2025-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemedia',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
