# Generated by Django 5.2.6 on 2025-11-17 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exerciseList', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=16)),
                ('is_published', models.BooleanField(default=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=0)),
                ('genres', models.ManyToManyField(blank=True, related_name='workouts', to='workoutLog.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_step_order', models.PositiveIntegerField(default=1)),
                ('current_set_index', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workoutLog.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('EXERCISE', 'Exercise'), ('REST', 'Rest'), ('NOTE', 'Note')], max_length=16)),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps_or_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_between_sets_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, max_length=32)),
                ('camera_required', models.BooleanField(default=False)),
                ('camera_overrides_json', models.JSONField(blank=True, default=dict, null=True)),
                ('rest_duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_message', models.CharField(blank=True, max_length=200)),
                ('note_title', models.CharField(blank=True, max_length=160)),
                ('note_body_md', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout_steps', to='exerciseList.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workoutLog.workout')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CompletedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_index', models.PositiveSmallIntegerField()),
                ('reps_done', models.PositiveIntegerField(default=0)),
                ('seconds_done', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='workoutLog.workoutsession')),
                ('workout_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='workoutLog.workoutstep')),
            ],
            options={
                'ordering': ('workout_step', 'set_index'),
            },
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'workout'), name='uniq_active_session_per_workout'),
        ),
        migrations.AddConstraint(
            model_name='workoutstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'EXERCISE'), ('exercise__isnull', False), ('sets__gt', 0), ('reps_or_seconds__gt', 0)), ('kind__in', ['REST', 'NOTE']), _connector='OR'), name='step_exercise_fields_valid'),
        ),
        migrations.AddConstraint(
            model_name='workoutstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'REST'), ('rest_duration_sec__gt', 0)), ('kind__in', ['EXERCISE', 'NOTE']), _connector='OR'), name='step_rest_fields_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutstep',
            unique_together={('workout', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='completedset',
            unique_together={('session', 'workout_step', 'set_index')},
        ),
    ]
